# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5fd931a1162451fb9d1dfec9a9ba6ce9791295bd9871f8363cde097fc9fed2e6c01c9771e4d7f4d07b4edc447ccdd74a50696effc07f2973782340580401cfc

test:
  secret_key_base: d10179fb44960cda7ea33171badd1d81045f49858cbcae49e8073353866d57d639317b513db934b20276f52bb03c34151941acf9e62fab36e5d44a0405b2d8d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
